In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"D:\my notebook\nlp-aih\clinical_data.csv")

In [6]:
df.head()

record_id diagnostic_category  \
0          1                Acne   
1          2                Acne   
2          3                Acne   
3          4                Acne   
4          5                Acne   

                                clinical_observation  
0  Scarring, including icepick and boxcar scars, ...  
1      Acne concentrated on the chest and shoulders.  
2     Acne is triggered by wearing masks or helmets.  
3  Deep, painful cystic lesions on the jawline an...  
4  Skin feels rough and bumpy due to numerous sma...

In [7]:
x = list(df["clinical_observation"])
y = df["diagnostic_category"]

In [8]:
x

['Scarring, including icepick and boxcar scars, from previous acne.',
 'Acne concentrated on the chest and shoulders.',
 'Acne is triggered by wearing masks or helmets.',
 'Deep, painful cystic lesions on the jawline and back.',
 'Skin feels rough and bumpy due to numerous small comedones.',
 'Inflammatory lesions are the predominant lesion type.',
 'Patient reports a family history of severe acne.',
 'Whiteheads and blackheads are the predominant lesion type.',
 'Mild comedonal acne with scattered open and closed comedones.',
 'Moderate inflammatory acne with papules, pustules, and some nodules.',
 'Mild comedonal acne with scattered open and closed comedones.',
 'Occasional flares with painful, deep-seated lesions.',
 'Acne is accompanied by oily scalp and dandruff.',
 'Acne leaves red marks that persist for months.',
 'Individual lesions take a long time to heal.',
 'Moderate inflammatory acne with papules, pustules, and some nodules.',
 'Oily skin with enlarged pores, particularly 

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()
y = le.fit_transform(y)

In [93]:
decode = le.inverse_transform(y)

In [98]:
decode.tolist()

['Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 'Acne',
 

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [12]:
import nltk
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
voc_size = 500

In [14]:
one_repo = [one_hot(words , voc_size) for words in x]

In [15]:
one_repo

[[68, 343, 28, 68, 420, 229, 348, 445, 389],
 [389, 20, 406, 160, 442, 68, 225],
 [389, 439, 478, 474, 133, 133, 341, 187],
 [467, 490, 281, 247, 406, 160, 429, 68, 341],
 [17, 395, 5, 68, 445, 313, 1, 375, 249, 226],
 [92, 247, 46, 160, 317, 255, 273],
 [101, 65, 369, 490, 194, 106, 228, 389],
 [13, 68, 38, 46, 160, 317, 255, 273],
 [107, 367, 389, 274, 103, 152, 68, 392, 226],
 [422, 92, 389, 274, 148, 87, 68, 71, 289],
 [107, 367, 389, 274, 103, 152, 68, 392, 226],
 [335, 66, 274, 490, 467, 355, 247],
 [389, 439, 164, 474, 399, 78, 68, 492],
 [389, 139, 11, 333, 292, 449, 192, 291],
 [377, 247, 12, 369, 473, 124, 1, 83],
 [422, 92, 389, 274, 148, 87, 68, 71, 289],
 [399, 17, 274, 405, 348, 445, 476, 160, 479, 101],
 [389, 439, 491, 476, 355, 68, 361, 422],
 [17, 439, 395, 68, 35, 165, 474, 310, 250],
 [389, 152, 1, 377, 371, 1, 126, 178],
 [422, 92, 389, 274, 148, 87, 68, 71, 289],
 [467, 490, 281, 247, 406, 160, 429, 68, 341],
 [92, 247, 46, 160, 317, 255, 273],
 [17, 395, 5, 68, 4

In [16]:
from tensorflow.keras.layers import Embedding , Dense , Dropout , Bidirectional ,LSTM
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
set_len = 8

In [18]:
emb_doc = pad_sequences(one_repo , maxlen=set_len , padding="post")

In [19]:
emb_doc

array([[343,  28,  68, ..., 348, 445, 389],
       [389,  20, 406, ...,  68, 225,   0],
       [389, 439, 478, ..., 133, 341, 187],
       ...,
       [101, 439, 137, ..., 130,   0,   0],
       [490, 194, 106, ..., 279,   0,   0],
       [247,  46, 395, ...,   0,   0,   0]])

In [20]:
dim_size = 10

In [21]:
model = Sequential()
model.add(Embedding(voc_size , dim_size , input_length = set_len))

In [22]:
model.add(Bidirectional(LSTM(100)))
model.add(Dense(5 , activation="softmax"))

In [23]:
model.compile(loss="sparse_categorical_crossentropy" , optimizer="adam" , metrics=["accuracy"])

In [24]:
model.summary

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x0000013FC898D700>>

In [25]:
x_final = np.array(emb_doc)
y_final = np.array(y)

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
x_train , x_test ,y_train ,y_test = train_test_split(x_final , y_final , test_size=0.2 , random_state=1)

In [28]:
model.fit(x_train , y_train , epochs=10 , batch_size=64)

Epoch 1/10
11/11 [==============================] - 7s 12ms/step - loss: 1.6081 - accuracy: 0.2379
Epoch 2/10
11/11 [==============================] - 0s 11ms/step - loss: 1.5953 - accuracy: 0.3364
Epoch 3/10
11/11 [==============================] - 0s 11ms/step - loss: 1.5534 - accuracy: 0.4106
Epoch 4/10
11/11 [==============================] - 0s 10ms/step - loss: 1.3929 - accuracy: 0.4136
Epoch 5/10
11/11 [==============================] - 0s 11ms/step - loss: 1.1328 - accuracy: 0.4606
Epoch 6/10
11/11 [==============================] - 0s 10ms/step - loss: 0.8823 - accuracy: 0.6697
Epoch 7/10
11/11 [==============================] - 0s 10ms/step - loss: 0.6404 - accuracy: 0.8076
Epoch 8/10
11/11 [==============================] - 0s 11ms/step - loss: 0.4477 - accuracy: 0.8394
Epoch 9/10
11/11 [==============================] - 0s 11ms/step - loss: 0.3467 - accuracy: 0.8818
Epoch 10/10
11/11 [==============================] - 0s 10ms/step - loss: 0.2774 - accuracy: 0.9015


In [29]:
from sklearn.metrics import confusion_matrix , accuracy_score

In [30]:
y_pred = model.predict(x_test)

6/6 [==============================] - 1s 5ms/step


In [31]:
y_pred

array([[4.61165298e-04, 4.53412440e-03, 3.08798917e-05, 4.11051937e-04,
        9.94562805e-01],
       [2.16345210e-03, 2.23557249e-01, 2.76837438e-01, 2.81619489e-01,
        2.15822309e-01],
       [3.04693793e-04, 1.31661110e-02, 1.20498508e-03, 7.40462448e-03,
        9.77919579e-01],
       [9.96128082e-01, 3.86515632e-03, 2.57657166e-06, 1.10592033e-07,
        4.03199147e-06],
       [6.82753676e-09, 1.03693424e-06, 9.94580209e-01, 5.41744474e-03,
        1.36266578e-06],
       [8.20743226e-05, 1.25204762e-02, 6.65868744e-02, 8.93150985e-01,
        2.76595745e-02],
       [1.34802094e-05, 4.56076395e-03, 2.92461574e-01, 7.00155973e-01,
        2.80830357e-03],
       [5.96723112e-04, 1.72159635e-02, 1.11928486e-04, 1.26461301e-03,
        9.80810821e-01],
       [1.79076451e-05, 4.60682297e-03, 1.29810646e-01, 8.63386512e-01,
        2.17803149e-03],
       [1.80711581e-07, 1.25555580e-05, 9.83404100e-01, 1.65777411e-02,
        5.34389847e-06],
       [7.95600712e-01, 2.0094

In [32]:
y_pred_classes = np.argmax(y_pred, axis=1)

In [33]:
y_pred_classes

array([4, 3, 4, 0, 2, 3, 3, 4, 3, 2, 0, 4, 2, 2, 3, 3, 0, 4, 0, 0, 0, 1,
       3, 3, 4, 1, 4, 4, 3, 1, 1, 1, 0, 0, 3, 2, 4, 3, 1, 4, 4, 2, 0, 4,
       0, 1, 4, 2, 3, 1, 3, 3, 4, 2, 1, 0, 4, 1, 0, 2, 1, 3, 0, 2, 1, 4,
       0, 1, 3, 1, 1, 0, 3, 3, 0, 2, 4, 3, 4, 4, 1, 2, 4, 4, 1, 3, 0, 4,
       2, 0, 1, 1, 4, 1, 3, 0, 2, 3, 3, 1, 2, 2, 3, 3, 4, 0, 4, 3, 0, 1,
       4, 0, 2, 0, 4, 0, 2, 3, 3, 4, 3, 0, 1, 1, 1, 3, 3, 4, 0, 0, 4, 3,
       4, 3, 4, 0, 0, 2, 2, 2, 3, 4, 0, 1, 4, 3, 3, 3, 4, 2, 2, 1, 0, 4,
       2, 3, 4, 3, 4, 0, 4, 2, 0, 1, 0], dtype=int64)

In [34]:
confusion_matrix(y_test , y_pred_classes)

array([[32,  1,  0,  0,  0],
       [ 2, 24,  0,  0,  0],
       [ 0,  1, 25,  6,  0],
       [ 0,  1,  0, 32,  0],
       [ 0,  1,  0,  1, 39]], dtype=int64)

In [35]:
accuracy_score(y_test , y_pred_classes)*100

92.12121212121212

In [36]:
model.save("aih_nlp_model.h5")

In [37]:
# for i in range(0,100):
#     x_train , x_test ,y_train ,y_test = train_test_split(x_final , y_final , test_size=0.2 , random_state=i)
#     model.fit(x_train , y_train , epochs=10 , batch_size=64)
#     y_pred = model.predict(x_test)
#     y_pred_classes = np.argmax(y_pred , axis=1)
#     print(i)
#     print(confusion_matrix(y_test , y_pred_classes))
#     print(accuracy_score(y_test , y_pred_classes))

In [41]:
def txt_preprocessing(txt):
    one_repo = one_hot(txt , 500)
    text =  pad_sequences([one_repo] , maxlen=8 , padding="post")
    return np.array(text)

In [102]:
txt = "Deep, painful cystic lesions on the jawline and back."

In [103]:
result = txt_preprocessing(txt)

In [104]:
# result = np.argmax(result)

In [105]:
result

array([[490, 281, 247, 406, 160, 429,  68, 341]])

In [106]:
res = model.predict(result)

1/1 [==============================] - 0s 28ms/step


In [107]:
res = np.argmax(res)

In [110]:
txt_confidence = round(np.max(res) * 100, 2)

In [111]:
txt_confidence

0

In [108]:
decoded_label = le.inverse_transform([res])[0]

In [109]:
decoded_label

'Acne'

In [100]:
import pickle as pkl

In [101]:
with open("label_encoder.pkl", "wb") as f:
    pkl.dump(le, f)